export const en = {
  navAbout: 'About',
  navServices: 'Services',
  navPartners: 'Partnerships',
  navContacts: 'Contacts',
  aboutAbout: "About us",
  aboutDescription: "'FM Consultores Associados' was founded on May 25, 1990. <br> Its founder, Fernando Mateus, has a degree in Organization and Business Management, and he is registered in the Order of Certified Accountants since August 4, 1987 under number 23776. He is a member of the Governing Bodies of several private companies, he started his professional activity leading the Accounting Services of the Portuguese Industrial Association.",
  clientsClients: 'Our clients',
  clientsDescription:"Since its foundation our company has always grown and nowadays it has a large portfolio of customers from different sectors.",
  partnersPartnerships: 'Partnerships',
  servicesServices: 'Services',
  servicesAccountant: 'Accounting',
  servicesTax: 'Tax Calculation',
  servicesClientsManagement: 'Clients Management',
  servicesConsulting: 'Consulting',
  servicesHumanResources: 'Human Resources',
  contactsContacts: 'Contacts',
  contactsAddress: 'Address',
}; 

export const pt = {
  navAbout: 'Sobre nós',
  navServices: 'Serviços',
  navPartners: 'Parcerias',
  navContacts: 'Contactos',
  aboutAbout: 'Sobre nós',
  aboutDescription: "A “FM Consultores Associados” foi constituída em 25 de Maio de 1990. <br> O seu fundador Fernando Mateus é licenciado em Organização e Gestão de Empresa, inscrito da ordem dos Contabilistas Certificados desde 4 de agosto de 1987 com o numero 23776. É membro de Órgãos Sociais de diversas empresas privadas tendo iniciado a sua atividade profissional chefiando os Serviços de Contabilidade da Associação Industrial Portuguesa.",
  clientsClients: 'Os nossos clientes',
  clientsDescription:'Desde da sua fundação a nossa empresa veio sempre a crescer e conta com uma grande carteira de clientes de diferentes setores.',
  partnersPartnerships: 'Parcerias',
  servicesServices: 'Serviços',
  servicesAccountant: 'Contabilidade Organizada',
  servicesTax: 'Apuramento de Impostos',
  servicesClientsManagement: 'Gestão de Clientes',
  servicesConsulting: 'Consultoria',
  servicesHumanResources: 'Recursos Humanos',
  contactsContacts: 'Contactos',
  contactsAddress: 'Morada',
};
